---
title: "TELESUR-GDM"
subtitle: "Rapport Statistique -- V1.0"
author: 
    - name: "Dr Philippe MICHEL"
      affiliations:
        name: "Hôpital NOVO"
        department: "Unité de Soutien à la Recherche Clinique"
format: html
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE) 
expx <- FALSE
classeur <- "telesurgdm1.xls"
```

```{r}
#| label: lib

library(baseph)
library(janitor)
library(corrplot)
library(missMDA)
library(tidyverse)
library(lubridate)
library(labelled)
library(kableExtra)
library(forestmodel)
library(epiDisplay)
library(confintr)
library(missMDA)
library(colorspace)
library(visdat)
library(gtsummary)
library(FactoMineR)
library(factoextra)
```

```{r}
#| label: import

bno <- read_csv("datas/bnom.csv")
nax <- c("NA","na","NK","","A","K", "Non disponible")

ttf <- read_csv("datas/FACTRISK.csv",na = nax)
ttr <- read_csv("datas/CRACCT.csv",na = nax)
ttc <- read_csv("datas/COMPLICATIONS.csv",na = nax)
tt <- left_join(ttf,ttr,by = "SUBJID")
tt <- left_join(tt,ttc,by = "SUBJID") |> 
      mutate_if(is.character, as.factor) |>
    janitor::clean_names() |> 
  drop_na(accdte) |> 
  drop_na(21,16,18,23:33) |> 
  dplyr::select(-hospiton)

var_label(tt) <- bno$nom

  tt$imccalcul = bmiph(tt$imccalcul,lang = "eng" )
#
tt <-  tt |> 
   mutate(deltapoids = fingrospds - pds) |> 
  relocate(deltapoids, .after = fingrospds) |> 
mutate(suivi = as.factor(ifelse(as.numeric(str_sub(tt$accdte, -2))>18,"Application", "Papier")))
## Réordonnancement de tt$suivi
tt$suivi <- tt$suivi %>%
  fct_relevel(
    "Papier", "Application"
  )
 
var_label(tt$deltapoids) <- "Prise de poids pendant la grossesse"
var_label(tt$imccalcul) <- "BMI"

tt <- tt |> 
  select(-c(accdte,accttermjrs)) |> 
  mutate(terme = if_else(accttermsa<37,"Prématuré","À terme"))
var_label(tt$terme) <- "Terme"

## Recodage de tt$parit en tt$parit
tt$parit <- cut(tt$parit,
  include.lowest = TRUE,
  right = TRUE,
  dig.lab = 1,
  breaks = c(0, 1, 2, 3, 10),
  labels = c("1","2","3","4 et +")
)
var_label(tt$parit) <- "Parité"

#

```

## Description de la population

### La mère

```{r}
#| label: descmere
#| tbl-cap: Tableau descriptif -- Parturiente

tt |> 
  select(2:13,33) |> 
  tbl_summary(by = suivi,missing = "no") |>
    modify_header(label ~ " ") %>%
  bold_labels() |> 
  add_n() |> 
  add_p() |> 
  bold_p()
```

### L'accouchement

```{r}
#| label: descaccouch
#| tbl-cap: Tableau descriptif -- Accouchement

tt |> 
  select(33,15:19) |> 
   tbl_summary(by = suivi,missing = "no") |>
    modify_header(label ~ " ") %>%
  bold_labels() |> 
  add_n() |> 
  add_p() |> 
  bold_p()
```

### Critère principal

```{r}
#| label: crit1
#| tbl-cap: Critère principal

tt |> 
  select(33,15,17,20:32) |> 
   tbl_summary(by = suivi,missing = "no") |>
    modify_header(label ~ " ") %>%
  bold_labels() |> 
  add_n() |> 
  add_p() |> 
  bold_p()
```